import { test, expect } from "playwright/test";
import { mkdirSync } from "node:fs";
import { resolve } from "node:path";

const folder = resolve(".impeccable/review");

test("desktop and responsive web presentation", async ({ page, request }, info) => {
  test.skip(info.project.name !== "web", "Shared web/desktop presentation; native mobile is outside this redesign.");
  mkdirSync(folder, { recursive: true });
  await request.post("/control", { data: { reset: true } });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/web");
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: `${folder}/setup-light.png`, fullPage: true, animations: "disabled" });
  await page.getByRole("textbox", { name: "Player name" }).fill("Franz");
  await page.getByRole("button", { name: "Extended (6)", exact: true }).click();
  await page.getByRole("button", { name: "Start Game", exact: true }).click();
  await expect(page.getByRole("button", { name: "Re-roll (2)" })).toBeEnabled();
  await page.getByRole("button", { name: /^Die showing/ }).first().click();
  await expect(page.getByRole("button", { name: /^Die showing/ }).first()).toHaveAttribute("aria-pressed", "true");
  await page.screenshot({ path: `${folder}/desktop-light.png`, fullPage: true, animations: "disabled" });
  await page.getByRole("button", { name: "Switch to dark mode" }).click();
  await page.setViewportSize({ width: 1073, height: 838 });
  await page.screenshot({ path: `${folder}/user-1073-dark.png`, fullPage: true, animations: "disabled" });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${folder}/mobile-web-dark.png`, fullPage: true, animations: "disabled" });
  await page.getByRole("button", { name: "Switch to light mode" }).click();
  await page.screenshot({ path: `${folder}/mobile-web-light.png`, fullPage: true, animations: "disabled" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await expect(page.locator(".die").first()).toHaveCSS("transition-duration", "0s");
  await page.getByRole("button", { name: "Quit Game", exact: true }).click();
  await page.screenshot({ path: `${folder}/setup-mobile.png`, fullPage: true, animations: "disabled" });
  await page.setViewportSize({ width: 944, height: 685 });
  await page.goto("/desktop");
  await page.getByRole("textbox").fill("Franz");
  await page.getByRole("button", { name: "1 AI", exact: true }).click();
  await page.getByRole("button", { name: "Extended (6)", exact: true }).click();
  await page.getByRole("button", { name: "Start Game", exact: true }).click();
  await expect(page.getByRole("button", { name: "Re-roll (2)" })).toBeEnabled();
  await page.screenshot({ path: `${folder}/desktop-944.png`, fullPage: true, animations: "disabled" });
  const compactHeight = await page.locator(".app-frame").evaluate((element) => element.getBoundingClientRect().height);
  expect(compactHeight).toBeLessThanOrEqual(685);
  await expect(page.getByRole("row", { name: /Grand Total/ })).toBeInViewport();
  await page.setViewportSize({ width: 934, height: 655 });
  const hostedHeight = await page.locator(".app-frame").evaluate((element) => element.getBoundingClientRect().height);
  expect(hostedHeight).toBeLessThanOrEqual(655);
  await expect(page.getByRole("row", { name: /Grand Total/ })).toBeInViewport();
  await page.setViewportSize({ width: 944, height: 685 });
  await page.getByRole("button", { name: "Quit Game", exact: true }).click();
  await page.getByRole("textbox").fill("WWWWWWWWWWWWWWWWWWWW");
  await page.getByRole("button", { name: "3 AI", exact: true }).click();
  await page.getByRole("spinbutton", { name: "Or choose your own" }).fill("20");
  await page.getByRole("button", { name: "Start Game", exact: true }).click();
  await expect(page.getByRole("button", { name: /^Die showing/ })).toHaveCount(20);
  await page.screenshot({ path: `${folder}/desktop-20-dice.png`, fullPage: true, animations: "disabled" });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(944);
  await page.getByRole("row", { name: /Grand Total/ }).scrollIntoViewIfNeeded();
  await expect(page.getByRole("row", { name: /Grand Total/ })).toBeInViewport();
  await page.getByRole("button", { name: "Re-roll (2)" }).scrollIntoViewIfNeeded();
  await expect(page.getByRole("button", { name: "Re-roll (2)" })).toBeInViewport();
});
